AWSTemplateFormatVersion: '2010-09-09'
Description: 'StreamFlex - Master Stack (Reseau, ALB, ECS)'

Parameters:
  TemplateBucket:
    Type: String
    Description: Nom du bucket S3 contenant les templates enfants
  ProjectName:
    Type: String
    Default: streamflex
    Description: Nom du projet utilisé pour tagger les ressources
### DEBUT MODIFICATION ( NOÉ) ###
  # Ajout du paramètre pour gérer le nombre de conteneurs (Active/Passive)
  NbConteneurs:
    Type: Number
    Default: 2
    Description: Mettre à 2 pour la région Active, et 0 pour la région de Secours (Pilot Light)
  TeamPrefix:
    Type: String
    Description: Initiales de l'equipe pour l'unicite des buckets S3
### FIN MODIFICATION ( NOÉ) ###

Resources:
  # 1. Couche Réseau
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/streamflex-infra.yaml"

  # 2. Couche Load Balancer (Dépend du Réseau)
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/streamflex-alb.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2

  # 3. Couche ECS et Front-End (Dépend de l'ALB)
  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/streamflex-ecs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        NbConteneurs: !Ref NbConteneurs
        TeamPrefix: !Ref TeamPrefix
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        ECSSecurityGroupId: !GetAtt ALBStack.Outputs.ECSSecurityGroupId
        CatalogTargetGroupArn: !GetAtt ALBStack.Outputs.CatalogTargetGroupArn
        UserTargetGroupArn: !GetAtt ALBStack.Outputs.UserTargetGroupArn

Outputs:
  MasterALBUrl:
    Description: URL de l'Application Load Balancer
    # On va chercher l'output "ALBUrl" à l'intérieur de la sous-pile "ALBStack"
    Value: !GetAtt ALBStack.Outputs.ALBUrl