AWSTemplateFormatVersion: '2010-09-09'
Description: 'StreamFlex - Couche 3 : Cluster ECS Fargate, Microservices et Portail S3'

Parameters:
  ProjectName:
    Type: String
    Default: streamflex
  NetworkStackName:
    Type: String
    Default: StreamFlex-Network
  ALBStackName:
    Type: String
    Default: StreamFlex-ALB
  NbConteneurs:
    Type: Number
    Default: 2
    Description: Mettre à 2 pour la région Active, et 0 pour la région de Secours (Pilot Light)

Resources:
  # 1. Le Cluster ECS
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ProjectName}-cluster
      CapacityProviders:
        - FARGATE

  # 2. Définitions des Tâches (Le "moule" des conteneurs)
  CatalogTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ProjectName}-catalog-task
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      ContainerDefinitions:
        - Name: catalog-app
          Image: velfouille/streamflex-api:catalog
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp

  UserTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ProjectName}-user-task
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      ContainerDefinitions:
        - Name: user-app
          Image: velfouille/streamflex-api:user
          PortMappings:
            - ContainerPort: 5000
              Protocol: tcp

  # 3. Les Services ECS (Maintien en condition opérationnelle)
  CatalogService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${ProjectName}-catalog-svc
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref CatalogTaskDefinition
      DesiredCount: !Ref NbConteneurs
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet1"
            - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet2"
          SecurityGroups:
            - Fn::ImportValue: !Sub "${ALBStackName}-ECSSG"
      LoadBalancers:
        - ContainerName: catalog-app
          ContainerPort: 8080
          TargetGroupArn:
            Fn::ImportValue: !Sub "${ALBStackName}-CatalogTG"

  UserService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${ProjectName}-user-svc
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref UserTaskDefinition
      DesiredCount: !Ref NbConteneurs
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet1"
            - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet2"
          SecurityGroups:
            - Fn::ImportValue: !Sub "${ALBStackName}-ECSSG"
      LoadBalancers:
        - ContainerName: user-app
          ContainerPort: 5000
          TargetGroupArn:
            Fn::ImportValue: !Sub "${ALBStackName}-UserTG"

  # 4. Hébergement du Front-End (Portail S3)
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
### DEBUT MODIFICATION ( NOÉ) ###
      # Ajout de la région dans le nom pour permettre le multi-région S3
      BucketName: !Sub "s3-projet-m1-infra-cloud-${TeamPrefix}-${AWS::Region}"
### FIN MODIFICATION ( NOÉ) ###
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
### DEBUT MODIFICATION ( NOÉ) ###
            # Mise à jour de l'ARN  le nom dynamique du bucket
            Resource: !Sub "arn:aws:s3:::s3-projet-m1-infra-cloud-${TeamPrefix}-${AWS::Region}/*"
### FIN MODIFICATION ( NOÉ) ###

Outputs:
  FrontendURL:
    Description: "L'URL publique de ton site vitrine StreamFlex"
### DEBUT MODIFICATION ( NOÉ) ###
    Value: !Sub "http://s3-projet-m1-infra-cloud-${TeamPrefix}-${AWS::Region}.s3-website-${AWS::Region}.amazonaws.com"
### FIN MODIFICATION ( NOÉ) ###